name: Determine list of PR targets

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  test_pr_trigger:
    name: Determine list of PR targets
    runs-on: ubuntu-latest
    steps:
      - name: Prerequisites
        run: |
          sudo apt update
          sudo apt install -y jq curl git

      - name: Checkout target
        uses: actions/checkout@v4
        with:
          path: target_repo
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: "List changed files"
        run: |
          # Get the base commit so we can do a diff against it
          git -C target_repo fetch origin ${{ github.event.pull_request.base.sha }}

          echo "Different files:"
          git -C target_repo diff --name-only ${{ github.event.pull_request.base.sha }}
